Feature/kea 145 events
hyunghoseo/nykea-app pull request #68
Opened 2024-04-19 01:58 UTC by jiahn326

2024-04-25 20:05 UTC, doolri1276 requested changes

2024-04-25 20:05 UTC, doolri1276 commented on backend/tests/helpers/constructor.js
> +            "Fee": null,
Why were these changed to null?

2024-04-25 20:06 UTC, doolri1276 requested changes

2024-04-25 20:06 UTC, doolri1276 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
* Not related to this ticket

Looks like rebase is needed

2024-04-29 23:43 UTC, jiahn326 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
> -    {
Reverted 👍

2024-04-29 23:45 UTC, jiahn326 commented on backend/config/sync/admin-role.strapi-super-admin.json
Reverted 👍

2024-04-29 23:49 UTC, jiahn326 commented on backend/config/sync/core-store.core_admin_project-settings.json
Reverted 👍

2024-05-06 18:32 UTC, jiahn326 commented on backend/src/components/common/address2.json
Thank you! I just updated address as well :)

2024-05-06 18:32 UTC, jiahn326 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
> +          "Location.City",
Can we have a call with this?

2024-05-06 18:32 UTC, jiahn326 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
>            "en"
Can we have a call with this?

2024-05-17 01:14 UTC, doolri1276 commented on backend/tests/api/event/index.js
> +                console.log(data.body);
Could you remove the logs?

2024-05-17 01:14 UTC, doolri1276 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
Rebase is still needed

2024-05-17 01:14 UTC, doolri1276 commented on backend/tests/helpers/constructor.js
> +            "Fee": null,
Can we have any test values to have it tested? Same thing goes for Contact.

2024-05-22 06:10 UTC, jiahn326 commented on backend/tests/api/event/index.js
> +                console.log(data.body);
I removed. thank you!

2024-05-22 06:22 UTC, jiahn326 commented on backend/config/sync/admin-role.admin-lrh30qnl.json
I just did rebase. Could you please check if it is rebased well?

2024-05-22 19:40 UTC, doolri1276 approved these changes

2024-05-22 19:40 UTC, merged